### ISSUE TITLE
Antique vs Antique B1

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/ShipporiAntique#1]
Can you explain the difference between `Antique` and `Antique B1`. Comparing the Glyphs files, they appear to be practically identical, with eight glyphs only slightly different between them. 

It isn't clear to me why there are two fonts.

**Comment by aaronbell** [comment]
Ah, I see that there is a 'rounding' filter in the B1 variant. If that's the only difference, then we should dump the B1 glyphs file and export two instances—one with the filter applied and one without. We will need to process it through Glyphs beforehand, then can build from fonttools.

**Comment by fontdasu** [comment]
The B1 variant is a definition with rounded corners.

![sample5](https://user-images.githubusercontent.com/55616797/98437779-68777600-2128-11eb-8a7d-a9a410bacbd2.png)

I have never used fonttools. Is the Glyphs app not enough?

**Comment by fontdasu** [comment]
The B1 variant is a slightly smaller version of Kana.
This is because it is easier to read if the kana is small in a Japanese novel.

So you can't have one source.

**Comment by aaronbell** [comment]
All fonts on Google Fonts need to be buildable using FontTools. This also helps with ensuring consistency and control over the build process. 

Now, since this is using a Glyphs filter, we will need to preprocess the Glyphs file into UFOs before we can build it—but that isn't something you need to worry about. Given that `Antique` and `Antique B1` are pretty much identical (except for the filter), I suggest setting up two export instances in Glyphs—one with the export filer (and set the familyName), and one without. That way, when you export, you generate both versions from a single file. 

The advantage of this approach is that you don't have to manage two separate glyphs files and risk them getting out of sync. If you'd like, I can get this set up for you as part of my finalizing the build process.

**Comment by fontdasu** [comment]
I combined the sources into one by the method you suggested.
As you say, this is more efficient. :)
Please check the latest file.

**Comment by aaronbell** [comment]
Nice! Yes, definitely makes things simpler, right?
