### ISSUE TITLE
Glyphs missing extremes

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/ShipporiAntique#2]
A number of the Latin / Kana glyphs are missing extremes. Adding extremes is particularly important for autohinted TTF fonts as it ensures optimal rendering:

0042 B B
0044 D D
00D0 Ð Eth
0050 P P
00DE Þ Thorn
0052 R R
0053 S S
0055 U U
FF22 Ｂ B.full
FF24 Ｄ D.full
FF30 Ｐ P.full
FF32 Ｒ R.full
FF33 Ｓ S.full
FF35 Ｕ U.full
None  Q.ss01
None  Q.full.ss01
None  R.ss01
None  R.full.ss01
None  J.full.vert.ss01
None  Q.full.vert.ss01
None  R.full.vert.ss01
None  B.full.vert
None  D.full.vert
None  P.full.vert
None  R.full.vert
None  S.full.vert
None  U.full.vert
0061 a a
00E6 æ ae
0066 f f
0067 g g
0068 h h
006A j j
006D m m
006E n n
0072 r r
0074 t t
0075 u u
0079 y y
FF41 ａ a.full
FF46 ｆ f.full
FF47 ｇ g.full
FF48 ｈ h.full
FF4A ｊ j.full
FF4D ｍ m.full
FF4E ｎ n.full
FF52 ｒ r.full
None  g.ss01
None  g.full.ss01
FF54 ｔ t.full
FF55 ｕ u.full
None  a.full.vert
None  f.full.vert
None  g.full.vert
None  h.full.vert
None  j.full.vert
None  m.full.vert
None  n.full.vert
None  r.full.vert
None  t.full.vert
None  u.full.vert
None  y.full.vert
FF59 ｙ y.full
00AA ª ordfeminine
3006 〆 close-han
3005 々 iterationmark-han
3042 あ a-hira
3041 ぁ asmall-hira
3044 い i-hira
3043 ぃ ismall-hira
3046 う u-hira
3045 ぅ usmall-hira
3048 え e-hira
3047 ぇ esmall-hira
304A お o-hira
3049 ぉ osmall-hira
304B か ka-hira
3095 ゕ kasmall-hira
304C が ga-hira
304D き ki-hira
304E ぎ gi-hira
3050 ぐ gu-hira
3051 け ke-hira
3052 げ ge-hira
3055 さ sa-hira
3059 す su-hira
305B せ se-hira
305D そ so-hira
305E ぞ zo-hira
305F た ta-hira
3060 だ da-hira
3061 ち ti-hira
3062 ぢ di-hira
3066 て te-hira
3067 で de-hira
3068 と to-hira
306A な na-hira
306B に ni-hira
306C ぬ nu-hira
306D ね ne-hira
306E の no-hira
306F は ha-hira
3070 ば ba-hira
3072 ひ hi-hira
3073 び bi-hira
3075 ふ hu-hira
3079 べ be-hira
307B ほ ho-hira
307C ぼ bo-hira
307E ま ma-hira
307F み mi-hira
3080 む mu-hira
3081 め me-hira
3082 も mo-hira
3084 や ya-hira
3083 ゃ yasmall-hira
3086 ゆ yu-hira
3085 ゅ yusmall-hira
3088 よ yo-hira
3087 ょ yosmall-hira
3089 ら ra-hira
308B る ru-hira
308C れ re-hira
308F わ wa-hira
308E ゎ wasmall-hira
3091 ゑ we-hira
3092 を wo-hira
3093 ん n-hira
3094 ゔ vu-hira
30A2 ア a-kata
30A1 ァ asmall-kata
30A4 イ i-kata
30A3 ィ ismall-kata
30A6 ウ u-kata
30A5 ゥ usmall-kata
30A8 エ e-kata
30A7 ェ esmall-kata
30AA オ o-kata
30A9 ォ osmall-kata
30AB カ ka-kata
30F5 ヵ kasmall-kata
30AD キ ki-kata
30AF ク ku-kata
31F0 ㇰ kusmall-kata
30B1 ケ ke-kata
30F6 ヶ kesmall-kata
30B3 コ ko-kata
30B4 ゴ go-kata
30B5 サ sa-kata
30B7 シ si-kata
31F1 ㇱ sismall-kata
30B9 ス su-kata
31F2 ㇲ susmall-kata
30BB セ se-kata
30BD ソ so-kata
30BF タ ta-kata
30C1 チ ti-kata
30C4 ツ tu-kata
30C3 ッ tusmall-kata
30C6 テ te-kata
30C8 ト to-kata
31F3 ㇳ tosmall-kata
30CA ナ na-kata
30CB ニ ni-kata
30CC ヌ nu-kata
31F4 ㇴ nusmall-kata
30CD ネ ne-kata
30CF ハ ha-kata
31F5 ㇵ hasmall-kata
30D2 ヒ hi-kata
31F6 ㇶ hismall-kata
30D5 フ hu-kata
31F7 ㇷ husmall-kata
30DB ホ ho-kata
31F9 ㇹ hosmall-kata
30DC ボ bo-kata
30DE マ ma-kata
30DF ミ mi-kata
30E0 ム mu-kata
31FA ㇺ musmall-kata
30E1 メ me-kata
30E2 モ mo-kata
30E4 ヤ ya-kata
30E3 ャ yasmall-kata
30E6 ユ yu-kata
30E5 ュ yusmall-kata
30E8 ヨ yo-kata
30E7 ョ yosmall-kata
30E9 ラ ra-kata
31FB ㇻ rasmall-kata
30EA リ ri-kata
31FC ㇼ rismall-kata
30EB ル ru-kata
31FD ㇽ rusmall-kata
30EC レ re-kata
31FE ㇾ resmall-kata
30ED ロ ro-kata
31FF ㇿ rosmall-kata
30EF ワ wa-kata
30EE ヮ wasmall-kata
30F0 ヰ wi-kata
30F1 ヱ we-kata
30F2 ヲ wo-kata
30F4 ヴ vu-kata
3033 〳 repeatUpperhalf-kana
3034 〴 repeatVoicedUpperhalf-kana
FF12 ２ two.full
FF13 ３ three.full
FF15 ５ five.full
FF16 ６ six.full
FF18 ８ eight.full
FF19 ９ nine.full
0032 2 two
0033 3 three
0035 5 five
0036 6 six
0039 9 nine
2460 ① one.circled
2461 ② two.circled
2462 ③ three.circled
2464 ⑤ five.circled
2465 ⑥ six.circled
2468 ⑨ nine.circled
None  two.half
None  three.half
None  five.half
None  six.half
None  nine.half
None  two.full.vert
None  three.full.vert
None  five.full.vert
None  six.full.vert
None  eight.full.vert
None  nine.full.vert
00B9 ¹ onesuperior
00B2 ² twosuperior
00B3 ³ threesuperior
00BD ½ onehalf
00BC ¼ onequarter
00BE ¾ threequarters
002C , comma
003B ; semicolon
3003 〃 dittomark
303D 〽 partalternationmark
FE45 ﹅ sesamedot
FE46 ﹆ whitesesamedot
FF20 ＠ at.full
None  comma.half
None  semicolon.half
FF1B ； semicolon.full
None  semicolon.full.vert
0028 ( parenleft
0029 ) parenright
007B { braceleft
007D } braceright
FF5B ｛ braceleft.full
FF5D ｝ braceright.full
FE37 ︷ braceleft.full.vert
FE38 ︸ braceright.full.vert
None  parenleft.half
None  parenright.half
FF08 （ parenleft.full
FF09 ） parenright.full
FE35 ︵ parenleft.full.vert
FE36 ︶ parenright.full.vert
301C 〜 wavedash
None  wavedash.vert
201A ‚ quotesinglbase
201E „ quotedblbase
201C “ quotedblleft
201D ” quotedblright
2018 ‘ quoteleft
2019 ’ quoteright
None  quotedblleft.full
None  quotedblright.full
None  quoteleft.full
None  quoteright.full
3001 、 comma-han
FE11 ︑ comma-han.vert
0024 $ dollar
00A3 £ sterling
007E ~ asciitilde
00B5 µ micro
2660 ♠ spadeBlackSuit
2663 ♣ clubBlackSuit
2668 ♨ hotsprings
0040 @ at
00A7 § section
2669 ♩ quarternote-musical
266A ♪ note-musical
266B ♫ notedbl-musical
266C ♬ beamedsixteenthnotes-musical
None  corporationSquare.vert
None  heiseieraSquare.vert
None  meizieraSquare.vert
None  syouwaeraSquare.vert
None  taisyoueraSquare.vert
02BC ʼ apostrophemod
02BB ʻ commaturnedmod
309E ゞ voicediteration-hira
30FC ー prolonged-kana
30FD ヽ iteration-kata
None  voicedcomb-kana.001
32FF ㋿ uni32FF
None  uni32FF.vert
E000  uniE000
E001  uniE001
E002  uniE002
E003  uniE003
E004  uniE004
E005  uniE005
E007  uniE007
E083  uniE083
E084  uniE084
E085  uniE085
E086  uniE086
E087  uniE087
E088  uniE088
E089  uniE089
E08A  uniE08A
E08B  uniE08B
E08D  uniE08D
E08F  uniE08F
E091  uniE091
E092  uniE092
E093  uniE093
E094  uniE094
E095  uniE095
E096  uniE096
E097  uniE097
E098  uniE098
E099  uniE099
E09E  uniE09E
E0A4  uniE0A4
E0E3  uniE0E3
E0E5  uniE0E5
E0E6  uniE0E6
None  uniE099.vert
None  uniE0DB.vert

I recommend using the Glyphs plugin `Red Arrows` to find where the issues are.

**Comment by fontdasu** [comment]
I have installed the Glyphs plugin Red Arrows, but do you know how to show only "extremes"? I also get errors other than "extremes".

<img width="1248" alt="スクリーンショット 2020-11-08 3 16 17" src="https://user-images.githubusercontent.com/55616797/98448674-10b12d00-2171-11eb-99d0-c3a772a8f963.png">

By the way, is it absolutely necessary to delete "extremes"?
It takes more than half a year to modify all fonts such as Shippori Mincho and ShipporiAntique and Mochiypop.

I can't fix this problem automatically and speedily. :(

**Comment by aaronbell** [comment]
No, unfortunately I don't know how to turn off all of the other red arrows :(. 

I'd suggest running `Paths > Add Extremes`. It doesn't work perfectly, but it'll take care of most situations:
<img width="885" alt="Screen_Shot_2020-11-08_at_9_35_52_AM_and_Screen_Shot_2020-11-08_at_9_36_00_AM" src="https://user-images.githubusercontent.com/8460297/98472152-fe9db180-21a5-11eb-9e45-6be452ab5a8c.png">

Now, ideally one would go back and clean up a lot of the situations where you now have extraneous points, but that is not a major issue in my mind.

**Comment by fontdasu** [comment]
I was able to select only glyphs that extremes missed and yay in Red Arrows! :)

<img width="1318" alt="スクリーンショット 2020-11-11 2 20 29" src="https://user-images.githubusercontent.com/55616797/98709257-7eee2d80-23c5-11eb-9516-376d675c0c9d.png">

After updating the glyphs version to 2.6.6 (1349), I got a dialog.

I filed a glyph that extremes is missing. Check the file of the file.

**Comment by aaronbell** [comment]
Looks good! Thanks :)
