### ISSUE TITLE
Glyphs in PUA

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/ShipporiAntique#3]
I'm confused about this set of glyphs present in the PUA:
<img width="1140" alt="Screen Shot 2020-11-06 at 1 33 04 PM" src="https://user-images.githubusercontent.com/8460297/98416977-f7a36180-2034-11eb-96c6-7eee0b7d0e80.png">

Is it common for the dakuten and dakuon to be used on all of these kana? And I think that it would be more efficient to use anchors, ccmp and the combining forms of dakuten/dakuon to generate these kana combinations when they might show up rather than filling space in the PUA.

**Comment by aaronbell** [comment]
Similarly, I see that you have added a substitution in the ccmp for all of the voiced kana:
`sub ha-hira voicedcomb-kana by ba-hira;`

Is this a common issue that needs to be addressed? My understanding is that more IMEs will automatically swap to the correct kana.

**Comment by fontdasu** [comment]
This font is often used by users who write novels and manga in Japan. The user loves this spec.

See the number of retweets in this article.
https://twitter.com/_zeroiti/status/1061120579057573888?s=20

There are only a few fonts with this specification, which is a feature of my font.

**Comment by aaronbell** [comment]
Ok! No problem. 

My thought was to implement it in a similar way as Latin does diacritics—setting anchor points, and using the combining mark to position it. That saves you from needing to explicitly create the glyph with the mark. But I'm OK with keeping these as is.
