### ISSUE TITLE
Latin design ill-suits Kana design

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/ShipporiAntique#5]
<img width="1007" alt="Screen Shot 2020-11-06 at 1 48 16 PM" src="https://user-images.githubusercontent.com/8460297/98417927-bad86a00-2036-11eb-99e7-7544881e321a.png">

The Kana design is very much derived from a brush, whereas the Latin is a sans serif and they do not suit one another. Suggest replacing the Latin set with a design more appropriate for the Kana.

**Comment by fontdasu** [comment]
This font is designed to be used in Japanese manga balloons.
In Japan, there is a font category called Antigochi, which is derived from Kana brush, and Kanji and Latin combine sans serif.
This style has been around for over 60 years in the Japanese publishing industry.
So, if I change the Latin language to a design that suits Kana, it will be difficult for Japanese users to use, so I will not change it.

![sample3](https://user-images.githubusercontent.com/55616797/98436323-e2563200-211d-11eb-9a7f-dd1da86e68d8.jpg)

**Comment by tanukifont** [comment]
I fully agree with fontdasu.
The combination of brushed kana and gothic CJK/Latin characters is a very familiar combination in Japanese comics.
Since this font was designed for the use of comic artists, I think the design should remain as it is.

**Comment by aaronbell** [comment]
As I mentioned on the other thread, thanks for the additional context. Given the intent of the font, I'm OK with this :)
