### ISSUE TITLE
Unintended outline in minus

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/ShipporiAntique#6]
<img width="825" alt="Screen Shot 2020-11-06 at 1 52 22 PM" src="https://user-images.githubusercontent.com/8460297/98418229-4e119f80-2037-11eb-915c-c9994fe69082.png">

Please remove the random paths from the minus (and all related glyphs)

**Comment by fontdasu** [comment]
I checked it in the latest font file, but the random paths was removed. Please check again.

**Comment by aaronbell** [comment]
Ah I see. It looks like the issue is not in "ShipporiAntiqueM" but is in "ShipporiAntiqueMKanaLantenOnly". This is the problem with having multiple glyphs files to cover the same character set :)
