### ISSUE TITLE
Review new TTFs

### ISSUE THREAD

**Issue by aaronbell** [fontdasu/ShipporiAntique#7]
I've pushed an update to the repository adding a Glyphs source for the font and new python-based build process. Please review the [font here](https://github.com/fontdasu/ShipporiAntique/tree/master/fonts/ttf) and let me know if it meets your expectations 😄 

The new build process takes quite some time, unfortunately, but happily I'm able to preserve the rounding as a post-production step by remote building from Glyphs.

**Comment by fontdasu** [comment]
I checked the file.
The font style name is
It was Regular,
I wanted to spell R, M, D, B, E for each weight.

Shippori Antique is medium weight, so I wanted to add "M".

**Comment by fontdasu** [comment]
By the way, can I build with glyph files?

Can only you build?

**Comment by aaronbell** [comment]
Thanks! For the font style naming, I followed the [Google Spec here](https://github.com/googlefonts/gf-docs/tree/master/Spec#static-fonts). Is that an issue?

In order to produce the exact same ttf files that I created, you need to use the build script. However, you can certainly still build the font from the Glyphs file—in fact, the first step in the build script is to export the fonts out of Glyphs. So you'd get pretty similar results!

**Comment by fontdasu** [comment]
Font style names follow Google specifications.

This Shippori Antique Not regular.
I want you to make it medium.

**Comment by aaronbell** [comment]
Hmm. 

As you consider this heavier than a Regular and it is a single weight font, then it would probably make sense to name it `Shippori Antique One Regular` per [this specification](https://github.com/googlefonts/gf-docs/tree/master/Spec#single-weight-families). That way, if the weight range is expanded in the future, it won't cause problems. Let me think about this.

**Comment by fontdasu** [comment]
By the way, I would like to make a Shippori Antique Bold weight in the future.

Since ancient times, medium and bold fonts have been the most in demand in the Japanese publishing industry.

**Comment by aaronbell** [comment]
Here's the complication. The Google Fonts API requires that _all families_ contain one font that is set at weight 400, and has the moniker `Regular`. Unfortunately, that is not something that I can change. 

We can certainly call the font `Shippori Antique Medium`, but it will have to be at weight 400 (rather than 500) and will have a subfamily name of `Regular`. So it'll be `Shippori Antique Medium Regular`. If in the future we update the font to add a `Regular` weight at 400, there's a possibility that someone would get a different weight than they expect. 

So, I'd suggest we set the font name as `Shippori Antique One Regular` for now, and then when more weights are added in the future, we can revisit how the font family is named holistically. What do you think?

**Comment by fontdasu** [comment]
Yes, I will follow your suggestion. This time, the name Shippori Antique One Regular is fine.

**Comment by aaronbell** [comment]
Thanks! Will implement that.
